Fix uninitialized autoptrs
These codepaths trigger errors like this:

        /usr/include/glib-2.0/glib/gmacros.h:1361:10: error: ‘source_object’ may be used uninitialized [-Werror=maybe-uninitialized]
         1361 |     { if (_ptr) (cleanup) ((ParentName *) _ptr); }                                                              \
              |          ^
        /usr/include/glib-2.0/glib/gmacros.h:1379:3: note: in expansion of macro ‘_GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS’
         1379 |   _GLIB_DEFINE_AUTOPTR_CLEANUP_FUNCS(TypeName, TypeName, func)
              |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        /usr/include/glib-2.0/gobject/gobject-autocleanups.h:31:1: note: in expansion of macro ‘G_DEFINE_AUTOPTR_CLEANUP_FUNC’
           31 | G_DEFINE_AUTOPTR_CLEANUP_FUNC(GObject, g_object_unref)
              | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        ../libeos-payg/manager.c: In function ‘epg_manager_new_finish’:
        ../libeos-payg/manager.c:576:22: note: ‘source_object’ was declared here
          576 |   g_autoptr(GObject) source_object;
              |                      ^~~~~~~~~~~~~
        cc1: all warnings being treated as errors

While they are unconditionally initialized, in all cases it is by
functions which can return NULL. So this may be triggering the warning.
The explicit initialization to NULL never hurts, anyway.