Partially revert "tests: Tell Meson our tests emit TAP output"
This reverts the hunks of 15f0d9319f29c56cdd345b67892013786084921b
which affect the tests written in C, as opposed to the Python ones.

In my environment, this only showed a warning like:

    Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.

but for JP there are many other errors:

     8/11 eos-payg:eos-payg / manager                      SKIP            0.11s
    Unknown TAP version. The first line MUST be `TAP version <int>`. Assuming version 12.
    stdout:  1: UNKNOWN: /manager/load-empty: OK
    [...]
    ERROR: Unknown TAP output lines for a supported TAP version.
    This is probably a bug in the test; if they are not TAP syntax, prefix them with a #

This is not essential. Revert.

https://phabricator.endlessm.com/T34768